### ISSUE TITLE
Unable to download taskonomy

### ISSUE THREAD

**Issue by AlexSunNik** [EPFL-VILAB/omnidata-tools#1]
Hello. Thanks for the nice work.
Running the following command:
`omnitools.download all --components taskonomy --subset fullplus   --dest ./omnidata_starter_dataset/   --connections_total 40 --agree`
to download taskonomy dataset finishes immediately and downloads nothing. I tried the following debug command:
```
omnitools.download rgb normals point_info \
  --components replica taskonomy \
  --subset debug \
  --dest ./omnidata_starter_dataset/ --agree-all
```
and it works fine.

**Comment by alexsax** [comment]
Thanks for flagging this and including examples~ I just pushed a fix that should address this. You can install it with `pip install--upgrade omnidata-tools`

Fix notes: The script was interpreting `all` as a domain itself, rather than as a signifier to just skip the domain filtering. `omnitools.download rgb normals point_info --components taskonomy --subset fullplus --dest ./omnidata_starter_dataset/ --connections_total 40 --agree` should have also worked--but now the original command works as expected.

Closing, but please reopen if the fix didn't work.

**Comment by FYtrace** [comment]
@alexsax Thanks for your great work. Similar to @AlexSunNik question. Running blendedmvg & hypersim datasets downloading commands will finish immediately and downloads nothing. Commands as follows: 
`omnitools.download rgb depth_zbuffer --components blendedmvg/or hypersim --subset fullplus/or others --dest ./omnidata_starter_dataset/ --connections_total 40 --agree`. 
It seems `filter_models` return 0 models.
